FROM node:20-alpine AS deps
WORKDIR /app
COPY package*.json ./
RUN npm ci

FROM node:20-alpine AS build
WORKDIR /app
COPY --from=deps /app/node_modules ./node_modules
COPY . .
RUN npm run build

FROM joseluisq/static-web-server:2-alpine
COPY --from=build /app/dist /public
ENV SERVER_ROOT=/public \
    SERVER_PORT=80 \
    SERVER_HOST=0.0.0.0 \
    SERVER_FALLBACK_PAGE=/public/404.html
EXPOSE 80
