# docker-compose.uat.yml
# Lokasi Eksekusi: Void (UAT)
# Domain: zetena.my.id

services:
  landing:
    image: zetenadev-landing:latest
    container_name: zetenadev-landing
    restart: unless-stopped
    networks:
      - infra-network
    labels:
      caddy: zetena.my.id
      caddy.reverse_proxy: "{{upstreams 80}}"

networks:
  infra-network:
    external: true
